name: Petstore API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --alluredir=allure-results

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results

  Publish-report:
    if: always()
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          unzip allure-2.27.0.zip
          sudo mv allure-2.27.0 /opt/
          sudo ln -s /opt/allure-2.27.0/bin/allure /usr/local/bin/allure

      - name: Generate report
        run: |
          [ -d "gh-pages/history" ] && cp -r gh-pages/history/* allure-results/history/ || true
          allure generate allure-results -o allure-report --clean

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
          keep_files: true